version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - mvn package
      - mv target/mavenWebApp.war mavenWebApp.war
artifacts:
  files:
    - mavenWebApp.war
    - .ebextensions/**/*